### ISSUE TITLE
Release with `package_info_plus: ^8.0.0`

### ISSUE THREAD

**Issue by Chralu** [kauemurakami/app_version_update#30] opened 2024-05-20 13:31 UTC
Hello,

Thanks for that useful package :)

I see you recently upgraded dependencies to use `package_info_plus: ^8.0.0`. 
Do you have other changes planned before the next release ?

For now, I'll point on your latest commit ;)

Thanks for your help.

**Comment by Macacoazul01** [comment] 2024-05-27 23:57
@kauemurakami we are still having to use another fork because this one depends on `package_info_plus ^6.0.0 `

Are you planning another release?

**Comment by romatallinn** [comment] 2024-05-31 07:40
@kauemurakami @pom11 yo

**Comment by romatallinn** [comment] 2024-05-31 07:45
@Macacoazul01 @Chralu not that I recommend this way of doing things, but you can use it as such, until (or if) they release it.

```
app_version_update:
  git:
    url: https://github.com/kauemurakami/app_version_update
    ref: 499047d
```

**Comment by Macacoazul01** [comment] 2024-06-12 01:55
im already using my fork with the pub update, tks @romatallinn!

@kauemurakami when are you planning to release?

**Comment by kauemurakami** [comment] 2024-06-18 16:34
Sorry, I've been very busy these last few months, last time I couldn't reproduce the example on my machine even though I was running all my other projects normally, I'll redo some things this week, if you have any ideas you can contribute a PR, I'll pay attention to the package this week!

**Comment by kauemurakami** [comment] 2024-06-18 19:47
Hello @Macacoazul01 @Chralu @romatallinn I just published version 5.0.0, I was having difficulty updating the example, and I discovered that the `country` specification was causing this error, I tested it with an app of mine in the store with a low version like "4.5.0" and with Facebook which is predefined in the example.
My Mac no longer supports xcode for this latest version of Flutter 😢, if anyone identifies an error on iOS, please let me know.
Test it and don't forget to open an issue if there is a problem, I will work on automatic closure after updating a mandatory update.
I will close this issue, but can reopen in error case, tkhs for patience.

**Comment by kauemurakami** [comment] 2024-06-18 21:44
I test with facebook version "468.1.0.56.78", and example 1.0.0, so bad news ... don't wor with "normal" version example 4.17.0, i working in this NOW. sorry

**Comment by kauemurakami** [comment] 2024-06-18 23:33
Test with `5.0.1`

**Closed** 2024-06-19 17:08 UTC
